=== ServerlessOpsIO/backstage-aws-resource-collector/data/handlers/AddAccountToCatalog/data.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Account data",
    "type": "object",
    "properties": {
        "Id": {
            "type": "string"
        },
        "Arn": {
            "type": "string"
        },
        "Email": {
            "type": "string"
        },
        "Name": {
            "type": "string"
        },
        "Status": {
            "type": "string"
        },
        "JoinedMethod": {
            "type": "string"
        },
        "JoinedTimestamp": {
            "type": "string"
        },
        "Tags": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "Key": {
                        "type": "string"
                    },
                    "Value": {
                        "type": "string"
                    }
                },
                "additionalProperties": false
            }
        }
    },
    "additionalProperties": false
}

=== ServerlessOpsIO/backstage-aws-resource-collector/data/handlers/ProcessEcsClusters/data.json
{
    "Id": "123456789012",
    "Arn": "arn:aws:organizations::123456789012:account/o-q4ulo3gwzx/123456789012",
    "Email": "master@example.com",
    "Name": "master",
    "Status": "ACTIVE",
    "JoinedMethod": "CREATED",
    "JoinedTimestamp": "2025-01-03T15:21:04.065434-05:00",
    "Tags": [
        {
            "Key": "org:system",
            "Value": "mock_system"
        },
        {
            "Key": "org:domain",
            "Value": "mock_domain"
        },
        {
            "Key": "org:owner",
            "Value": "group:mock_group"
        }
    ]
}
